spring.datasource.url=jdbc:mysql://localhost:3306/medical_pro_db?createDatabaseIfNotExist=true
spring.datasource.username=root
# Dynamically reads your local DB_PASSWORD environment variable so it's never pushed to GitHub again
spring.datasource.password=${DB_PASSWORD:leul1990}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=e11efedf24de197cb7d745a09e58e468fbedbd1aaeb5dd33e9bfa940770749ddd2cff4dcca2a0b728620e1c7c8b13c7a13829d8f16f362d0d2859a1f678d450d
